### ISSUE TITLE
Tutorial 4. Roads: code for generatePolygon could be simplified

### ISSUE THREAD

**Issue by Lecrapouille** [gniziemazity/virtual-world#2]
Hi ! 

Your rectangle "envelop" computation looks complex, based on the orientation of the vector P1P2 (using cos, loop and angle addition at least in your YT video):

https://github.com/gniziemazity/virtual-world/blob/b9482cf3ec387c9d46b0b7c7a5976e85e91d0f72/4.%20Roads/js/primitives/envelope.js#L7-L26

One day I had to crop rectangle inside a picture. I used the norm of P1 and P2 plus a margin (in my case for both side). Here is my python code:
```
def norm(P1, P2, scale):
  length = np.sqrt((P1[0] - P2[0])**2 + (P1[1] - P2[1])**2)
  dx = P2[0] - P1[0]
  dy = P2[1] - P1[1]
  N = [-dy * scale / length, dx * scale / length]
  return N

margin = 24
N = norm(P1, P2, margin)
M = norm(P1, P1 + N, margin)
rect = [P1 - N + M, P1 + N + M, P2 + N - M, P2 - N - M]
```

Here is the link https://github.com/Lecrapouille/Highway/blob/a2e4f38674bf0b80dd638a299b8bd6d1b445e106/src/ECUs/ParkingSlotDetectionECU/crop.py#L31C1-L34C60

I have not tested my code in your project (`M = norm(P1, P1 + N, margin)` shall be `M = norm(P1, P1 + N)` to get https://youtu.be/3Aqe7Tv1jug?feature=shared&t=666), whathever the  mean, I opened this ticket just for indication.

**Comment by Lecrapouille** [comment]
Sorry for the spam, your method is better since we need to know the starting angle and ending angle for the cercles but not 0 .. 180

**Comment by gniziemazity** [comment]
Ah ok... I wouldn't be surprised if many of the things can be made more efficient, though :-)
When teaching something I implement things in an easy to understand way first, only then I teach how to make it more efficient (maybe).

**Comment by Lecrapouille** [comment]
Thanks, keep going your YT videos, they are interesting. I will try to reuse your poylgon/envelop algo for my C++ project
